# Provision a Vagrant VM with our usual web-stack technologies
---
- hosts: all
  become: yes
  gather_facts: no

  vars:
   pg_hba_additions:
    - host all all 0.0.0.0/0 trust
   pg_listen_all: True
   node_version: v4.4.3

  tasks:
  - name: apt cache
    apt: update_cache=yes cache_valid_time=86400

  - name: install python
    apt: name='python-simplejson'

  - name: install common
    apt: name='software-properties-common'

  - apt_repository: repo="ppa:ansible/ansible"

  - name: ensure apt cache is up to date
    apt: update_cache=yes cache_valid_time=86400

  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - ansible
        - git
        - postgresql
        - curl
        - build-essential
        - libssl-dev

  - name: Download nvm
    shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash
    become: true
    become_user: vagrant
    register: nvm_installed

  - name: Show nvm_installed output
    debug:
      msg: '{{nvm_installed}}'


  - name : source bash profiles
    shell: source ~/.bashrc
    args:
      executable: /bin/bash
    register: sourced
    when : nvm_installed | success
    become: true
    become_user: vagrant

  - name: Show sourced output
    debug:
      msg: '{{sourced}}'

  - name: Install specified node version using the nvm command and set it as default
    shell: '[ -s "$NVM_DIR/nvm.sh"  ] && . "$NVM_DIR/nvm.sh" && nvm install {{ node_version }} && nvm alias default {{ node_version }}'
    when: sourced|success
    become: true
    become_user: vagrant
    environment:
      NVM_DIR: /home/vagrant/.nvm

  - name: Add a directory for node Ansible callback plugins
    file: path=/usr/share/ansible/plugins/callback state=directory

  - name: Add module to create human readable output
    template:
      src: templates/human_log.py
      dest: /usr/share/ansible/plugins/callback

  - name: Add pretty-print module to Ansible
    blockinfile:
      dest: /etc/ansible/ansible.cfg
      marker: "# {mark} ANSIBLE MANAGED CALLBACK PLUGIN BLOCK "
      insertafter: '#callback_plugins   = /usr/share/ansible/plugins/callback'
      content: |
        callback_plugins   = /usr/share/ansible/plugins/callback

  - name: Install Grunt and Mocha
    shell: '[ -s "$NVM_DIR/nvm.sh"  ] && . "$NVM_DIR/nvm.sh" && npm i -g grunt-cli mocha'
    become: true
    become_user: vagrant
    environment:
      NVM_DIR: /home/vagrant/.nvm
